# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmisObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smisobj_name', models.TextField(verbose_name='название объекта')),
                ('smisobj_adress', models.TextField(blank=True, null=True, verbose_name='адрес объекта')),
                ('smisobj_category', models.TextField(blank=True, null=True, verbose_name='категория объекта')),
            ],
            options={
                'db_table': 'smisobj',
            },
        ),
    ]
