# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smisobj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smisobj',
            options={'verbose_name': 'СМИС объект', 'verbose_name_plural': 'СМИС объекты'},
        ),
        migrations.RenameField(
            model_name='smisobj',
            old_name='smisobj_adress',
            new_name='smisobj_address',
        ),
    ]
